### ISSUE TITLE
Saving video throws error

### ISSUE THREAD

**Issue by surajde16** [buzzcard/cordova-library-helper#5]
In iOS , am using LibraryHelper.saveVideoToLibrary(onSuccess, onError, path, albumName);
my video format is MP4.

Am getting onError function with message as "Path is not valid video file".

But am able to play the same video path in video plugin that am using.

Please let me know.
 if i have do some changes for file path or i have to change the video file format

**Comment by jacobo3d** [comment]
I'm getting the same issue on iOS:

`Video file:///var/mobile/Containers/Data/Application/[NUMBER_HERE]/Library/NoCloud/myVideo.mp4 cannot be saved to the saved photos album: Error Domain=NSURLErrorDomain Code=-1100 "The requested URL was not found on this server." UserInfo={NSUnderlyingError=0x14770ff80 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}, NSErrorFailingURLStringKey=file:///file:/var/mobile/Containers/Data/Application/[NUMBER_HERE]/Library/NoCloud/myVideo.mp4, NSErrorFailingURLKey=file:///file:/var/mobile/Containers/Data/Application/[NUMBER_HERE]/Library/NoCloud/myVideo.mp4, NSURL=file:///file:/var/mobile/Containers/Data/Application/[NUMBER_HERE]/Library/NoCloud/myVideo.mp4, NSLocalizedDescription=The requested URL was not found on this server.}
[3441:1668190] Path is not a valid video file`

**Comment by coryjthompson** [comment]
Could you please post an example path that is playable in the video plugin?

**Comment by GustavsR** [comment]
I am also getting the same error on iOS.
This is code I am using - 
```
 window.requestFileSystem(LocalFileSystem.PERSISTENT, 0, function (fileSystem) {

        var fileTransfer = new FileTransfer();
        var uri = encodeURI(file); // file = valid mp4 file (this link is also used in html <video> tag
        var path = fileSystem.root.toURL() + "video.mp4";

        fileTransfer.download(
            uri,
            path,
            function(entry) {
                alert(JSON.stringify(entry)); // Video has been downloaded, just verify file path
                LibraryHelper.saveVideoToLibrary(function () {
                     alert(1); // Just to make sure it is success callback
                 }, function (e) {
                     alert(e);
                 }, entry.nativeURL, 'myName');
              },
              function(error) {
                   alert(error);
              },
              false
          );
 });
```

So all I get is error callback with message  "Path is not valid video file".

Any advice on this?

**Comment by coryjthompson** [comment]
Thank you for providing a code sample. 

I've updated the plugin and your sample code is now working. 

    cordova plugin remove cordova-library-helper
    cordova plugin add cordova-library-helper

Let me know if it fixes it on your end.

**Comment by GustavsR** [comment]
Yes, it works now!
Thanks!

**Comment by coryjthompson** [comment]
Perfect 👍🏼
