### ISSUE TITLE
iOS: SaveImageToLibrary - memory

### ISSUE THREAD

**Issue by pliablepixels** [buzzcard/cordova-library-helper#8]
Hi there, I am using cordova file to save a "blob" to disk - lets call it "foo.gif". This is an animated GIF of several frames. I then use this plugin's `saveImageToLibrary` function to move the downloaded file to the iOS gallery.

It looks like it reads the full image into memory first - does [this line](https://github.com/buzzcard/cordova-library-helper/blob/master/src/ios/LibraryHelper.m#L30) also covert to base64 ? The memory requirements are huge for an animated GIF (several 100MB for a 60 frame GIF, that takes around 20MB on disk). Is there any way to save it to gallery without loading the full image to memory (and I am assuming that line also converts to base64)

**Comment by ryanwilliams83** [comment]
I have just learned that the ALAssetsLibrary has been depreciated as of iOS9.
https://developer.apple.com/reference/assetslibrary/alassetslibrary

It has been replaced by the Photos framework.
https://developer.apple.com/reference/photos

You may wish to try the PHAssetChangeRequest.creationRequestForAssetFromImage(atFileURL fileURL: URL) function to achieve what you’re attempting to do.
https://developer.apple.com/reference/photos/phassetchangerequest/1624059-creationrequestforassetfromimage

I have no plans to port our plugin to the Photos framework at this time.
However if and when we do we would likely avoid loading the image into RAM if possible.

Warm Regards
Ryan Williams

**Comment by pliablepixels** [comment]
Thanks Ryan - I'll explore PHAssetChangeRequest - looks promising.
